CHAR, INT, FLOAT, DOUBLE, VOID = 'CHAR', 'INT', 'FLOAT', 'DOUBLE', 'VOID'
CHAR_CONST, INTEGER_CONST, REAL_CONST = 'CHAR_CONST', 'INTEGER_CONST', 'REAL_CONST'
STRING = 'STRING'

ADD_OP, SUB_OP = 'ADD_OP', 'SUB_OP'
MUL_OP, DIV_OP, MOD_OP = 'MUL_OP', 'DIV_OP', 'MOD_OP'
INC_OP, DEC_OP = 'INC_OP', 'DEC_OP'
AND_OP, OR_OP, XOR_OP = 'AND_OP', 'OR_OP', 'XOR_OP'
LEFT_OP, RIGHT_OP = 'LEFT_OP', 'RIGHT_OP'
LT_OP, GT_OP = 'LT', 'GT'
LE_OP, GE_OP = 'LE_OP', 'GE_OP'
EQ_OP, NE_OP = 'EQ_OP', 'NE_OP'
LOG_AND_OP, LOG_OR_OP, LOG_NEG = 'LOG_AND_OP', 'LOG_OR_OP', 'LOG_NEG'

ASSIGN, MUL_ASSIGN, DIV_ASSIGN = 'ASSIGN', 'MUL_ASSIGN', 'DIV_ASSIGN'
MOD_ASSIGN, ADD_ASSIGN, SUB_ASSIGN = 'MOD_ASSIGN', 'ADD_ASSIGN', 'SUB_ASSIGN'
LEFT_ASSIGN, RIGHT_ASSIGN = 'LEFT_ASSIGN', 'RIGHT_ASSIGN'
AND_ASSIGN, XOR_ASSIGN, OR_ASSIGN = 'AND_ASSIGN', 'XOR_ASSIGN', 'OR_ASSIGN'

LPAREN, RPAREN = 'LPAREN', 'RPAREN'
LBRACKET, RBRACKET = 'LBRACKET', 'RBRACKET'

COMMA, DOT, SEMICOLON, HASH = 'COMMA', 'DOT', 'SEMICOLON', 'HASH'
COLON, QUESTION_MARK = 'COLON', 'QUESTION_MARK'

ID = 'ID'
IF, ELSE, FOR, WHILE, RETURN, DO = 'IF', 'ELSE', 'FOR', 'WHILE', 'RETURN', 'DO'
BREAK, CONTINUE = 'BREAK', 'CONTINUE'

EOF = 'EOF'




